# Generated by Django 4.2.2 on 2023-07-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
    ]
