# Generated by Django 4.2.2 on 2023-07-01 10:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0002_remove_userprofile_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
