# Generated by Django 4.2.2 on 2023-07-02 12:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_alter_userprofile_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
