# Generated by Django 4.2.2 on 2023-07-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0004_alter_userprofile_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PickupAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='authorisation.userprofile')),
            ],
        ),
    ]
