# Generated by Django 4.2.2 on 2023-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0007_alter_pickupaddress_profile_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
