# Generated by Django 4.2.2 on 2023-07-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0008_userprofile_middle_name_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupaddress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorisation.userprofile'),
        ),
    ]
