# Generated by Django 4.2.2 on 2023-08-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0010_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
