# Generated by Django 4.2.2 on 2023-08-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_delete_shoppingcartorder'),
        ('authorisation', '0011_delete_shoppingcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatalogItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.catalogitem')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorisation.userprofile')),
            ],
        ),
    ]
