# Generated by Django 4.2.2 on 2023-08-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0012_shoppingcartorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartorder',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
