# Generated by Django 4.2.2 on 2023-06-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0001_initial'),
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelery_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authorisation.userprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authorisation.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
