# Generated by Django 4.2.2 on 2023-07-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0004_alter_userprofile_telephone_number'),
        ('dispatcher', '0002_alter_jewelery_request_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jewelery_Request',
            new_name='JeweleryRequest',
        ),
    ]
