# Generated by Django 4.2.2 on 2023-07-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_articleorder_amount_alter_articleorder_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='articleorder',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
