# Generated by Django 4.2.2 on 2023-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_remove_articlerequest_profile_remove_order_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequest',
            name='size',
            field=models.IntegerField(),
        ),
    ]
