# Generated by Django 4.2.2 on 2023-07-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_articlerequest_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequest',
            name='article',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='articlerequest',
            name='size',
            field=models.CharField(max_length=32),
        ),
    ]
