# Generated by Django 4.2.2 on 2023-07-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_articlerequest_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRequestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.factory')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.articlerequest')),
            ],
        ),
    ]
