# Generated by Django 4.2.2 on 2023-07-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_articlerequestanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerequestanswer',
            name='factory',
        ),
    ]
