# Generated by Django 4.2.2 on 2023-07-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_articlerequestanswer_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequestanswer',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
