# Generated by Django 4.2.2 on 2023-07-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_catalogitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='photo',
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('CatalogItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='webapp.catalogitem')),
            ],
        ),
    ]
