# Generated by Django 4.2.2 on 2023-07-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_catalogitemimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitemimage',
            name='photo',
        ),
    ]
