# Generated by Django 4.2.2 on 2023-08-07 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_remove_catalogitemimage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.factory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.jewelerytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
