# Generated by Django 4.2.2 on 2023-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_shoppingcartorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCartOrder',
        ),
    ]
