# Generated by Django 4.2.2 on 2023-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_delete_shoppingcartorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='price',
            field=models.IntegerField(default=9999999999999),
            preserve_default=False,
        ),
    ]
