# Generated by Django 4.2.2 on 2023-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_catalogitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
