# Generated by Django 4.2.2 on 2023-08-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_articlerequestanswer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequest',
            name='size',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
