# Generated by Django 4.2.2 on 2023-07-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequestanswer',
            name='size',
            field=models.IntegerField(),
        ),
    ]
