# Generated by Django 4.2.2 on 2023-07-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_alter_articlerequestanswer_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleRequestAnswer',
        ),
    ]
